name: pplm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - boto3=1.18.21
  - ipywidgets=7.6.5
  - python=3.8
  - pip
  - notebook=6.4.6
  - pytorch=1.7.1
  - pandas=1.3.4
  - cudatoolkit=11.0
  - seaborn=0.11.2
  - tabulate=0.8.9
  - pip:
    - nltk==3.2.5
    - colorama==0.4.4
    - torchtext==0.3.1
    - transformers==3.4.0
    - textstat==0.7.2
